# This is a basic workflow to help you get started with Actions

name: Update CLient/Server

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-client:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Zip all
        run: |
          cd /home/minecraft/actions-runner/work/modpack/modpack/client
          rm /var/www/html/client.zip
          zip -r /var/www/html/client.zip *
# This workflow contains a single job called "build"
  update-server:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Update
        run: |
          cd /home/minecraft/actions-runner/work/modpack/modpack/client
          screen -r minecraft -X quit
          rm -R /home/minecraft/mods/
          rm -R /home/minecraft/config/
          cp -R mods/ /home/minecraft/
          cp -R config/ /home/minecraft/
          cd /home/minecraft
          su minecraft
          ./start.sh
